ipAddr: 127.0.0.1
server:
  port: 9050
spring:
  application:
    name: mall-ware
  datasource:
    username: luna
    password: luna
    url: jdbc:mysql://${ipAddr}:3306/mall-wms?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${ipAddr}:8848
    sentinel:
      transport:
        dashboard: ${ipAddr}:8333
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: ${ipAddr}
    virtual-host: /
    listener:
      simple:
        # 手动确认接受消息
        acknowledge-mode: manual
  zipkin:
    base-url: ${ipAddr}:9411/
    # 关闭我们自动的服务发现功能
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.firenay.mall.ware: debug
myRabbitmq:
  MQConfig:
    queues: stock.release.stock.queue
    delayQueue: stock.delay.queue
    eventExchange: stock-event-exchange
    routingKey: stock.locked
    letterRoutingKey: stock.release
    # 库存自动过期时间 单位:(毫秒)
    ttl: 900000